#ifndef __TELEIOS_RUNTIME_MEMORY__
#define __TELEIOS_RUNTIME_MEMORY__

#include "teleios/defines.h"

typedef enum {
    TL_MEMORY_BLOCK,
    TL_MEMORY_SERIALIZER,
    TL_MEMORY_CONTAINER_STACK,
    TL_MEMORY_CONTAINER_LIST,
    TL_MEMORY_CONTAINER_NODE,
    TL_MEMORY_CONTAINER_MAP,
    TL_MEMORY_CONTAINER_MAP_ENTRY,
    TL_MEMORY_CONTAINER_ITERATOR,
    TL_MEMORY_STRING,
    TL_MEMORY_ULID,
    TL_MEMORY_PROFILER,
    TL_MEMORY_SCENE,
    TL_MEMORY_ECS_COMPONENT,
    TL_MEMORY_THREAD,
    TL_MEMORY_MAXIMUM
} TLMemoryTag;

#endif // __TELEIOS_RUNTIME_MEMORY__