#ifndef __TELEIOS_CORE_MEMORY_TYPES__
#define __TELEIOS_CORE_MEMORY_TYPES__

typedef enum {
    TL_MEMORY_BLOCK,
    TL_MEMORY_SERIALIZER,
    TL_MEMORY_CONTAINER_STACK,
    TL_MEMORY_CONTAINER_LIST,
    TL_MEMORY_CONTAINER_NODE,
    TL_MEMORY_CONTAINER_ITERATOR,
    TL_MEMORY_STRING,
    TL_MEMORY_ULID,
    TL_MEMORY_PROFILER,
    TL_MEMORY_SCENE,
    TL_MEMORY_MAXIMUM
} TLMemoryTag;

typedef struct TLMemoryArena TLMemoryArena;

#endif //__TELEIOS_CORE_MEMORY_TYPES__
