#ifndef TELEIOS_MESSAGING_CODES
#define TELEIOS_MESSAGING_CODES

#define TL_MESSAGE_APPLICATION_QUIT 2500

#define TL_MESSAGE_WINDOW_ 2600

#define TL_MESSAGE_INPUT_ 2700

#define TL_MESSAGE_TOTAL 3000

#endif // TELEIOS_MESSAGING_CODES
