@startuml
'https://plantuml.com/sequence-diagram

participant main.c

participant platform.c
participant OS
participant memory.c
participant config.c
participant GLFW
participant window.c
participant graphics.c
participant simulation.c
participant input.c
participant application.c
participant thread.c

main.c -> platform.c : tl_platform_initialize
platform.c -> OS : tl_(winapi|lnx)_initialize
platform.c <-- OS
platform.c -> memory.c : tl_memory_initialize
platform.c <-- memory.c
platform.c -> config.c : tl_config_initialize
platform.c <-- config.c
platform.c -> GLFW : glfwInit
platform.c <-- GLFW
platform.c -> window.c : tl_window_create
platform.c <-- window.c



platform.c -> graphics.c : tl_graphics_initialize
graphics.c -> thread.c : tl_thread_create(tl_graphics_thread)
graphics.c <-- thread.c
platform.c <-- graphics.c


platform.c -> simulation.c : tl_simulation_initialize
simulation.c -> thread.c : tl_thread_create(tl_simulation_thread)
simulation.c <-- thread.c
platform.c <-- simulation.c

platform.c -> input.c : tl_input_initialize
platform.c <-- input.c
main.c <-- platform.c

main.c -> application.c : tl_application_initialize
main.c <-- application.c

main.c -> application.c : tl_application_run
main.c <-- application.c

main.c -> application.c : tl_application_terminate
main.c <-- application.c

main.c -> platform.c : tl_platform_terminate
main.c <-- platform.c

@enduml