@startuml
'https://plantuml.com/component-diagram


[MainThread] --> [GraphicsThread] : create
[MainThread] --> [SimulationThread] : create
[MainThread] --> [NetworkThread] : create

note bottom of [GraphicsThread]
    Graphic IO
end note

note right of [MainThread]
    Program Initialization
    Resource Loading
    Program Termination
end note

note bottom of [SimulationThread]
    Client Logic Processing
end note

note bottom of [NetworkThread]
    Network IO
end note
@enduml